### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by candidosouza** [candidosouza/placework#1]
## Tasks

Configuração do projeto
- [x]  Docker
- [x] Configurações iniciais
- [x] Configurando o CI

### **Tarefas e Funcionalidades**

Cadastro de usuários e seus requisitos:
- [x]  Cadastrar novos usuários e novas empresas
    - [x] Criação dos models
        - [x] Usuários únicos
        - [x] Deixar o perfil do cadastro inativo, só será ativado com confirmação de cadastro
    - [x] Configuração do admin
    - [x] Configuração de dados fakes
    - [x] Criação das views
    - [x] Testes de integração das views
    - [x] Criação do formulário de cadastro
    - [x] Testes Unitários do formulário de Cadastro
    - [x] Estruturação e estilização do formulário de cadastro
    - [x] Validações do formulário de cadastro e configurações
        - [x] Configurações de CPF ou CNPJ
        - [x] Empresas com vários endereços
        - [x] Todos o campos devem ser preenchidos
- [x]  Atualizar dados de usuários
- [x] Cadastro com confirmação de email
    - [x] Envio de email com código
    - [x] Esqueceu senha
- [ ] Refinamentos
    - [ ]  Segurança
        - [ ] Para atualização, verificar se o usuário é o dano dos dados
        - [ ] Cadastrar endereço, verificar se a empresa é dona dos dados
        - [ ] Verificar as páginas se precisa de autenticação
        - [ ] Redirecionar usuários para que os mesmos não acessarem páginas que não precisam, exemplo login, usuário autenticado não precisa acessar, redirecionar para home
        - [ ] Usuários/Empresas não podem acessar dados de outros
    - [x] Usuários não pode acessar o cadastro de endereços, seu endereço será criado no cadastro, fazer redirecionamento
- [x] login de usuário
  - [x] verificar se o perfil está ativo, caso contrario informar uma mensagem de ativação
  - [x] Recuperação de senha
      - [x] gerar código relacionado ao usuário
      - [x] enviar código por email
      - [x] receber código e validar
      - [x] gerar senha com expiração de 1 hora
      - [x] enviar nova senha  por email
      - [x] no link, forçar o usuário a trocar senha
- [x] Sair do sistemas
    - [x] configurar view do logout, como redirecionamento para home
- [ ] Verificar possibilidade de Design Patterns
- [ ] Verificar possibilidade de logs
- [ ] Comentários explicativos de códigos (DOC)
- [ ] Verificar CI SonarCloud, não está pegando o coverage.xml, verificar tempo, senão desabilitar
- [ ] Limpeza de código, verificar tempo
- [ ] Possibilidade de otimização, verificar tempo
- [ ] Documentação README
- [ ] Possibilidade de envio para produção (AWS)

### **Tela de Inicial**:
- [x] Solicita o cadastro de novo usuário
    - [x] Executa a chamada de formulário de cadastro
- [x] Realiza autenticação de usuário existente
    - [x] O usuário só terá acesso se a senha e email informado forem validados
    - [x] Após 5 tentativas o usuário é bloqueado e não poderá acessar o sistema até que a senha seja trocada
- [x] Recuperação de senha
    - [x] O código só será enviado se o email informado for igual ao email do cadastro
    - [x] Se o código informado for válido será gerada uma nova senha e enviada por email
    - [x] A Nova senha tem prazo de expiração de 1 hora para troca

### **Cadastro de usuário**
- [x] Cadastrar novo usuário
    - [x] O Cadastro só será salvo se todas as informações forem informadas e validadas
    - [x] Se o Tipo do cadastro for profissional os dados de razão social e CNPJ não devem ser exibidos
    - [x] Se o Tipo do cadastro for empresa os dados de nome e CPF não devem ser exibidos
    - [x] O email informado deve ser confirmado através de envio de um código de validação
    - [x] Deve ser verificado se o usuário já existe na base de dados através dos campos chave únicos
    - [x] Uma empresa pode ter vários endereços associados
    - [x] Os atributos não podem estar em branco
- [x] Atualizar dados de usuário
    - [x] Deve permitir atualizar somente os dados de nome/razão social e senha dos usuários
    - [x] A senha não pode coincidir com as 5 últimas utilizadas
    - [x] Os atributos não podem estar em branco
    - [x] O cadastro só será atualizado se todas as informações forem validadas

## Requisitos do sistema

Funcionais

 - Funcionalidades Core
	Usuários podem se cadastrar no sistema para pesquisar espaços compartilhados
	Empresas podem se cadastrar no sistema para compartilhar seus espaços
	Para pesquisar os espaços compartilhados, o usuário precisa estar logado
	Para empresa compartilhar seus espaços, precisa estar logado ao sistema

 - Funcionalidade de Suporte
	O usuário se cadastra no sistema
	As empresas se cadastra no sistema
	As empresas compartilha seus espaços
	Os usuários pesquisa e faz a locação de um espaço

Não Funcionais

 - Características
  O sistema precisa ser rápido / baixa latência
  O sistema precisa ter alta disponibilidade
  O sistema precisa ser escalável
  Consistência de dados
  
 - Teorema CAP
	Disponibilidade
	Consistência de dados
